# Generated by Django 4.2.2 on 2023-06-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exclusivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=200)),
                ('precio_full', models.IntegerField()),
                ('imagen_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mejores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=200)),
                ('duracion', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=3)),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=1)),
                ('imagen_url', models.CharField(max_length=200)),
            ],
        ),
    ]
