# Generated by Django 4.2.2 on 2023-06-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exclusivas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=200)),
                ('precio_full', models.IntegerField()),
                ('precio_descuento', models.IntegerField()),
                ('imagen_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Exclusivos',
        ),
    ]
