# Generated by Django 4.2.2 on 2023-06-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_mejores_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='exclusivas',
            name='calificacion',
            field=models.DecimalField(decimal_places=2, default=4.8, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mejores',
            name='calificacion',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
