# Generated by Django 4.2.2 on 2023-06-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_exclusivas_calificacion_alter_mejores_calificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('imagen_url', models.CharField(max_length=200)),
            ],
        ),
    ]
